# Run AMS on MullerBrown potential 

In [1]:
from IPython.core.display import  HTML
# Jupyter display settings
display(HTML("<style>.container { width:90% !important; }</style>"))

General imports 

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from potentials.MullerBrown import MullerBrown
from simulations.AMSSimulation import AMSOverdampedLangevin, AMSLangevin

Definie the potential 

In [4]:
pot = MullerBrown()
pot.set_SigmaR_position(1.)
pot.set_SigmaP_position(1.)

Define reaction coodinate for ams. 

In [5]:
def xi_overdamped(x):
    """Reaction coordinate 
    :param x: numpy array with ndim=2 and shape = [any, 2]
    :return xi: numpy array with ndim=1 and shape = [any, 1]"""
    if pot.in_P(x[0]):
        return 10 ** 8
    if pot.in_R(x[0]):
        return -10 ** 8
    return -x[0, 1]

def xi_underdamped(x, p):
    """Reaction coordinate 
    :param x: numpy array with ndim=2 and shape = [any, 2]
    :return xi: numpy array with ndim=1 and shape = [any, 1]"""
    if pot.in_P(x[0]):
        return 10 ** 8
    if pot.in_R(x[0]):
        return -10 ** 8
    return -x[0, 1]

## AMS Overdamped 

Define AMS object 

In [23]:
beta = 0.05
dt = 0.0001
AMS_on_MB = AMSOverdampedLangevin(pot, xi_overdamped, beta, forward=True, dt=dt, threshold=10**(-5))

Sample initial condtions 

In [24]:
n_conditions = 50
ini_traj, ini_conds, _, n_steps = AMS_on_MB.sample_initial_conditions(n_conditions=n_conditions, save_gauss=False)
print(n_steps)

557


Do an AMS run 

In [25]:
n_rep = 50
k_min = 1

In [26]:
p, z_kills, replicas, total_md_steps = AMS_on_MB.ams_run(ini_conds, n_rep, k_min, return_all=True, save_gauss=False)

In [27]:
print(total_md_steps)

29149


In [28]:
probas = []
n_conditions = 50
n_rep = 50
k_min = 1
for i in range(10):
    ini_traj, ini_conds, _, n_steps = AMS_on_MB.sample_initial_conditions(n_conditions=n_conditions, save_gauss=False)
    p, z_kills, replicas, total_md_steps = AMS_on_MB.ams_run(ini_conds, n_rep, k_min, return_all=True, save_gauss=False)
    probas.append(p)

In [29]:
probas

[0.0009646153197592934,
 0.0007998030888532938,
 0.0012255216773852647,
 0.0006875819201222022,
 0.0006206226342963488,
 0.00040785969409784674,
 0.00044984848486903986,
 0.0010026828457073494,
 0.0008867868022300415,
 0.0008810201520279123]

In [30]:
print(np.mean(probas))
print(np.std(probas, ddof=1))

0.0007926342619348593
0.0002547319105599031


## AMS underdamped 

Define AMS object 

In [6]:
beta = 0.05
dt = 0.005
m = np.array([[1., 1.]])
gamma = np.array([[10**0, 10**0]])
AMS_on_MB = AMSLangevin(pot, xi_underdamped, m, gamma, beta, forward=True, dt=dt, threshold=10**(-5))

In [7]:
n_conditions = 500
ini_traj, ini_conds, _, n_steps = AMS_on_MB.sample_initial_conditions(n_conditions=n_conditions, save_gauss=False)
print(n_steps)

17101


Do an AMS run 

In [8]:
n_rep = 50
k_min = 1

In [9]:
p, z_kills, replicas, total_md_steps = AMS_on_MB.ams_run(ini_conds, n_rep, k_min, return_all=True, save_gauss=False)

In [10]:
print(total_md_steps)

27448


In [19]:
print(p)

0.0020662777006269528


In [20]:
probas = []
n_conditions = 200
n_rep = 200
k_min = 1
for i in range(10):
    ini_traj, ini_conds, _, n_steps = AMS_on_MB.sample_initial_conditions(n_conditions=n_conditions, save_gauss=False)
    p, z_kills, replicas, total_md_steps = AMS_on_MB.ams_run(ini_conds, n_rep, k_min, return_all=True, save_gauss=False)
    probas.append(p)

In [21]:
probas

[0.00025281113868051973,
 0.005045072612273326,
 0.0057188963496029865,
 0.000598814393232309,
 0.0008552546333523242,
 0.006677781718538542,
 0.008332989613390204,
 0.0026167846849069745,
 0.009978380085827741,
 0.00029376771978301743]

In [22]:
print(np.mean(probas))
print(np.std(probas, ddof=1))

0.004037055294958795
0.003603512892338199


In [34]:
x = pot.minP
y = pot.minR

In [37]:
np.column_stack([x,y])

array([[ 0.6234994 ,  0.02803776, -0.55822364,  1.44172584]])

In [38]:
x.shape

(1, 2)

In [50]:
u = np.column_stack([np.arange(0, 10, 6), np.arange(1, 10, 6)])

In [108]:
a = np.arange(0, 100).reshape(10, 10)

In [70]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
indices = np.column_stack([np.arange(0, 10, 6), np.arange(1, 10, 6)]).flatten("C")

In [106]:
indices


array([0, 1, 6, 7])

In [107]:
a[:, indices]

array([[ 0,  1,  6,  7],
       [10, 11, 16, 17],
       [20, 21, 26, 27],
       [30, 31, 36, 37],
       [40, 41, 46, 47],
       [50, 51, 56, 57],
       [60, 61, 66, 67],
       [70, 71, 76, 77],
       [80, 81, 86, 87],
       [90, 91, 96, 97]])

In [80]:
k = a[:, indices].reshape(len(a)*len(indices)//2, 2)

In [81]:
k.reshape(len(a), len(indices))

array([[ 0,  1,  6,  7],
       [10, 11, 16, 17],
       [20, 21, 26, 27],
       [30, 31, 36, 37],
       [40, 41, 46, 47],
       [50, 51, 56, 57],
       [60, 61, 66, 67],
       [70, 71, 76, 77],
       [80, 81, 86, 87],
       [90, 91, 96, 97]])

In [82]:
a[:, :2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [109]:
a = a[:, :3]
b = a.reshape(10, 1, 3) * np.ones([10,10, 3])

In [110]:
np.append(b, np.random.normal(size=([10, 10, 2])), axis=2).reshape(100, 5)

array([[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         1.35773877e-01, -1.23262690e+00],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         1.30785010e+00,  4.31401711e-01],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        -7.32588385e-01, -6.33232059e-01],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         1.56226634e+00,  5.36111503e-01],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        -1.64369900e+00,  1.94215005e+00],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        -7.80170670e-02, -5.11485888e-01],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         5.89138318e-02,  1.14413025e+00],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        -4.84894970e-01, -2.28839244e-03],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        -4.62857699e-01,  1.66286217e+00],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         1.38451965e-01